### ISSUE TITLE
Is it possible to add ldn support?

### ISSUE THREAD

**Issue by AnthonyViniciusMuller** [flathub/org.ryujinx.Ryujinx#2]

**Comment by Thog** [comment]
LDN version sources aren't available to the public yet, therefore it cannot be built here.

**Comment by rowbawts** [comment]
They're publicly released now, maybe consider publishing those under the Flathub beta branch?

**Comment by marysaka** [comment]
> They're publicly released now, maybe consider publishing those under the Flathub beta branch?

No that's no the case. See the roadmap https://github.com/Ryujinx/Ryujinx/issues/4716.
