### ISSUE TITLE
Enable aarch64 build

### ISSUE THREAD

**Issue by theofficialgman** [flathub/org.ryujinx.Ryujinx#39]
As the title said. Ryujinx itself has aarch64 support so that flatpak should as well.

**Comment by marysaka** [comment]
> As the title said. Ryujinx itself has aarch64 support so that flatpak should as well.

aarch64 is only supported on macOS atm and not Linux.

**Comment by gdkchan** [comment]
The JIT should work on aarch64 Linux as well. I was able to successfully run a few games on Raspberry Pi 4, but it's hard to find a Linux Arm board with decent Vulkan support and a good GPU. So in practice I wouldn't expect such a build to be very useful.

**Comment by theofficialgman** [comment]
hence why I want it enabled. I have multiple ARM devices in mind that have decent gpus (Nintendo Switch - Tegra-X1, and all the Nvidia Jetsons are more than capable with my `org.freedesktop.Platform.GL.nvidia-tegra` flatpaks <https://forums.developer.nvidia.com/t/gpu-hardware-accelerated-flatpaks-for-jetson-t210-t186-t194-and-t234/240787>) as well as vulkan drivers coming soon on Asahi Linux.

@marysaka please enable building on aarch64

**Comment by marysaka** [comment]
> @marysaka please enable building on aarch64

In the current state no, I will not. If we do enable it, it will just not work as we need to bootstrap some initial parts first.

For the whole release management we do need some natives build support for Linux arm64 **as we pin specific versions for some libraries even for FlatHub builds**.

That would require the following dependencies to support Linux ARM64 in CI (and probably others):
- [SDL2-CS](https://github.com/Ryujinx/SDL2-CS)
- [Ryujinx.Graphics.Nvdec.Dependencies](https://github.com/Ryujinx/Ryujinx.Graphics.Nvdec.Dependencies) (optional for FlatHub as we use org.freedesktop.Platform.ffmpeg but we started providing our own builds recently)
- libsoundio (We need to design a full CI for this as currently we still rely on old manually built versions)

To add to the injury, Github Actions don't provide any runners for ARM64 Linux at the moment so we would need to use an emulated environment or provide our own self-hosted runner running in qemu.

Now let's say we have all of this in place, you mentioned Asahi Linux but this target doesn't support 4KiB pages, we would need to ensure that .NET runtime and Ryujinx's JIT do behaves correctly with this memory configuration.

On my side, I don't have the time to tackle all of this now, and macOS packaging takes the priority as some bits are still missing here.

In any cases could you create an issue on our official repository?

**Comment by ArchemedIan** [comment]
It's been a year and I'd just like to point out there are now arm64 SBCs with GPUs capable of running a good amount of games (proven on their android builds.)  rk3588 based SBCs for instance have ok Vulkan performance and new drivers are planned for the future with better Vulkan support. 

Just throwing that out there. Arm64 Switch emulator ports are increasingly more commonly asked for in the discords of those SBCs with that SOC. And you already did the impossible with macOS.

**Comment by marysaka** [comment]
We enabled linux aarch64 build on main release, I will attempt to enable it on flathub hopefully this week.
